### ISSUE TITLE
alarm system triggered → alarm system is switched off

### ISSUE THREAD

**Issue by lu-mueller** [MrDrache333/Apple-HomeKit-Security-System-integration-for-Bosch-SmartHome#1]
If I set the alarm system to full protection in the HomeKit App and then try to trigger the alarm by opening a window, the alarm is not triggered instead the alarm system is switched off. Can somebody help me?

**Comment by MrDrache333** [comment]
Hi @lu-mueller,
can you show me the Flow you are using and the Values coming from the Input-Nodes and the Values going to HomeKit and the BSHC-Adapter?

**Comment by lu-mueller** [comment]
I have reinstalled everything. Now it works!
